name: my_reflection_app
description: A self-growth quest application.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  intl: ^0.19.0 # Stays at 0.19.0 to maintain compatibility with table_calendar
  # State Management
  provider: ^6.1.5
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  
  # Notifications
  flutter_local_notifications: ^17.2.4

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_timezone: ^4.1.1 # Рекомендуется указывать версию для стабильности
  fl_chart: ^1.0.0
  table_calendar: ^3.1.3 # Downgraded to resolve dependency conflict with intl
  firebase_core: ^3.15.1
  firebase_analytics: ^11.5.2
  http: ^1.4.0
  # cloud_functions: ^4.7.2 # Больше не используется

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.5.4
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon717.jpg"
  min_sdk_android: 21
