// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkvICyZY5m3s2Ro7zhxSZM6Cugx10Owzs',
    appId: '1:1013992488441:web:35edec33ae765d57ad1128',
    messagingSenderId: '1013992488441',
    projectId: 'my-reflection-app',
    authDomain: 'my-reflection-app.firebaseapp.com',
    storageBucket: 'my-reflection-app.firebasestorage.app',
    measurementId: 'G-6D5VDGTEM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGwJb0iZkPsJ3Ru1YhjYUDW06K0n93EN8',
    appId: '1:1013992488441:android:eb5b480e49b111c5ad1128',
    messagingSenderId: '1013992488441',
    projectId: 'my-reflection-app',
    storageBucket: 'my-reflection-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw0xuvf6LS4ZGt6NQR6TdMkIhKMgzaFfM',
    appId: '1:1013992488441:ios:d5ac995b29e25abead1128',
    messagingSenderId: '1013992488441',
    projectId: 'my-reflection-app',
    storageBucket: 'my-reflection-app.firebasestorage.app',
    iosBundleId: 'com.example.myReflectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw0xuvf6LS4ZGt6NQR6TdMkIhKMgzaFfM',
    appId: '1:1013992488441:ios:d5ac995b29e25abead1128',
    messagingSenderId: '1013992488441',
    projectId: 'my-reflection-app',
    storageBucket: 'my-reflection-app.firebasestorage.app',
    iosBundleId: 'com.example.myReflectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkvICyZY5m3s2Ro7zhxSZM6Cugx10Owzs',
    appId: '1:1013992488441:web:750ab2df6670cbebad1128',
    messagingSenderId: '1013992488441',
    projectId: 'my-reflection-app',
    authDomain: 'my-reflection-app.firebaseapp.com',
    storageBucket: 'my-reflection-app.firebasestorage.app',
    measurementId: 'G-T452NY7HGG',
  );
}
